routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::resource('products', 'ProductsController');
    Route::get('addToCart/{id}', 'AddToCartController@add')->name('products.addToCart');
    Route::get('cart', 'AddToCartController@getCart')->name('getCart');
    Route::get('/remove/{id}', 'AddToCartController@getRemoveItem')->name('product.remove');
    Route::get('/reduce/{id}', 'AddToCartController@getReduceByOne')->name('product.reduceByOne');
    Route::get('/checkout', 'AddToCartController@postCheckout')->name('checkout.post');
    Route::get('user/{id}', 'UserController@getProfile')->name('user.profile');
    Route::get('user', 'UserController@getAllCheckout')->name('all.profile');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use softDeletes ;

    protected $fillable = ['item', 'photo', 'description', 'price'];

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(9);
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Product::class);

        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Product::class);

        $path = $request->file('photo')->store('public/image');


        $product = new Product();
        $product->item=$request->item;
        $product->description=$request->description;
        $product->price=$request->price;
        $product->photo= basename($path);

        $product->save();

        return redirect()->route('products.index')->with(['message' => 'Product added successfully']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('update', Product::class);

        $product = Product::findOrFail($id);
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $path = $request->file('photo')->store('public/image');

        $product = Product::findOrFail($id);


        $product->item=$request->item;
        $product->description=$request->description;
        $product->price=$request->price;
        $product->photo= basename($path);
        $product->update();
        return redirect()->route('products.index')->with(['message'=>'Product updated successfully']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('delete', Product::class);

        $product = Product::findOrFail($id);
        Storage::delete('public/image/'.$product->picture);

        $product->delete();
        return redirect()->route('products.index')->with(['message' => 'Product deleted successfully']);
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div id="cart">
        <div class="container align1">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">Add New Product</div>

                        <div class="panel-body">
                            @if ($errors->count() > 0)
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
                            <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                Product Item:
                                <br/>
                                <input type="text" name="item" value="{{ old('title') }}"/>
                                <br/><br/>
                                Product Description:
                                <br/>
                                <textarea name="description" rows="7" cols="100">{{ old('description') }}</textarea>
                                <br/><br/>
                                Product Price:
                                <br/>
                                <input type="text" name="price" value="{{ old('price') }}"/>
                                <br/><br/>
                                Product image:
                                <br/>
                                <input type="file" name="photo"/>
                                <br/><br/>
                                <input type="submit" value="Submit" class="btn btn-default"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div id="cart">
        <div class="container align1">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">Edit Product</div>

                        <div class="panel-body">
                            @if ($errors->count() > 0)
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
                            <form action="{{ route('products.update', $product->id) }}" method="post" enctype="multipart/form-data">
                                <input type="hidden" name="_method" value="PUT">
                                {{ csrf_field() }}
                                Product Title:
                                <br/>
                                <input type="text" name="item" value="{{ $product->item }}"/>
                                <br/><br/>
                                Product Description:
                                <br/>
                                <textarea name="description" rows="7" cols="100">{{$product->description }}</textarea>
                                <br/><br/>
                                Product Price:
                                <br/>
                                <input type="text" name="price" value="{{ $product->price }}"/>
                                <br/><br/>
                                Product image:
                                <br/>
                                <input type="file" name="photo"/>
                                <br/><br/>
                                <input type="submit" value="Submit" class="btn btn-default"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @if (session('message'))
                <div class="alert alert-info">{{ session('message') }}</div>
            @endif
        </div>
        <div class="row">
            @can('create', \App\Product::class)
                <div class="col-md-12">
                    <a href="{{route('products.create')}}" class="btn btn-primary">Prideti</a>
                </div>
            @endcan

        </div>
        <div class="row">
            @forelse($products as $product)
                <div class=" col-md-4 card">
                    <div class="card__inner" style="background: url('/storage/image/{{$product->photo}}') no-repeat;background-size: 100%">
                        <h2>{{ $product->item }} <small>Series</small></h2>
                        <div class="card__buttons">
                            <a href="{{route('products.show', $product->id)}}">Info</a>
                            <a href="{{route('products.addToCart', $product->id)}}">Shop</a>
                        </div>
                    </div>
                    <h3 class="card__tagline">{{ $product->price }}</h3>
                    <div>
                        @can('update', \App\Product::class)
                            <a href="{{ route('products.edit', $product->id) }}" class="btn btn-default">Redaguoti</a>
                        @endcan

                        @can('delete', \App\Product::class)
                            <form action="{{ route('products.destroy', $product->id) }}" method="POST"
                                  style="display: inline"
                                  onsubmit="return confirm('Are you sure?');">
                                <input type="hidden" name="_method" value="DELETE">
                                {{ csrf_field() }}
                                <button class="btn btn-danger">Istrinti</button>
                            </form>
                        @endcan
                    </div>
                </div>
            @empty
                <div class="col-md-12">
                    <h3>No entries found.</h3>
                </div>
            @endforelse

        </div>

        {{ $products->links() }}
    </div>




@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="panel panel-primary">

                <div class="panel-heading">
                    {{$product->item}}
                </div>


                <div class="panel-body">
                    <div class="col-md-6">
                        {{$product->description}}
                    </div>

                    <div class="col-md-6" style="background: url('/storage/image/{{$product->photo}}') no-repeat;background-size: 100%; height: 300px">

                    </div>
                    <div class="col-md-3">
                        <div class="input-group form-param">
                            <span class="input-group-addon">Kaina</span>
                            <input id="importe" name="importe"
                                   class="form-control" placeholder="importe" type="text"
                                   disabled="disabled" value="{{$product->price}}">
                            <span class="input-group-addon" id="eur-addon">EUR</span>
                        </div><!-- .input-group -->
                    </div><!-- .col-md-3 -->


                </div><!-- .panel-body -->

                <div class="panel-footer">
                    <a class="btn-primary btn" href="{{route('products.index')}}">Atgal</a>
                </div>

            </div><!-- .panel -->

        </div>
    </div>

    @endsection